const data = {
  products: [
    {
      name: 'Nike Slim Shart',
      slug: 'nike-slim-shart',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'Hith quality shirts',
    },
    {
      name: 'Adidas Slim Shart',
      slug: 'adidas-slim-shart',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'Hith quality shirts',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pant',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'Hith quality pant ',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'Hith quality pant',
    },
  ],
};

export default data;
